### ISSUE TITLE
Lecture 2 slide "Defining the Relationship" missing closing brace

### ISSUE THREAD

**Issue by WimbledonLabs** [jzarnett/ece356#3]
The last line of "Defining the Relationship" does not have a closing `}`.

The line is currently
`where $\{(e_{1}, e_{2}, ..., e_{n})$ is a relationship.`

I would submit a pull request but I'm not sure whether it would be better to remove the initial curly brace, or to add one at the end.

**Comment by jzarnett** [comment]
Remove. Fixed in 734115f5c2615752de365eeb156eef5b26e9ee9c
